version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: zeno_backend 
    restart: always
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://zenith-redis:6379  # <-- Yeh Zenith wale container ka naam hai!
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://5.189.142.15:8080
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: zeno_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend